### PR TITLE
📝 Improve Error Message in NA Compiler

### LINKED ISSUE #792: RuntimeError when compiling neutral atom circuit
### System and Environment Information

detailed below

### Bug Description

I I am currently getting a compilation failure when dealing with a specific circuit. 

I am running on MacOS 26.0 with python 3.12.10 using QMAP mqt-core 3.2.1 mqt-qmap 3.3.1. 

When running a circuit with 63 qubits and a few entangling gates detailed at the end, these lines of codes return the error message

> code = compiler.compile(circuit)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: No path from start to any goal found.

My code is the 

>   circ = QuantumCircuit.from_qasm_file(path)
>     circuit = load(circ)
>     compiler = RoutingAwareCompiler(arch)
>     code = compiler.compile(circuit)

You can use any arch you want, provided it has enough traps for the 63 qubits.

The specific QASM file is 

OPENQASM 2.0;
include "qelib1.inc";
gate circuit_168 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(-pi/4) q0; ry(-pi/4) q1; ry(-pi/4) q2; ry(-pi/4) q3; ry(-pi/4) q4; ry(-pi/4) q5; ry(-pi/4) q6; ry(-pi/4) q7; ry(-pi/4) q8; ry(-pi/4) q9; ry(-pi/4) q10; ry(-pi/4) q11; ry(-pi/4) q12; ry(-pi/4) q13; ry(-pi/4) q14; ry(-pi/4) q15; ry(-pi/4) q16; ry(-pi/4) q17; ry(-pi/4) q18; ry(-pi/4) q19; ry(-pi/4) q20; ry(-pi/4) q21; ry(-pi/4) q22; ry(-pi/4) q23; ry(-pi/4) q24; ry(-pi/4) q25; ry(-pi/4) q26; ry(-pi/4) q27; ry(-pi/4) q28; ry(-pi/4) q29; ry(-pi/4) q30; ry(-pi/4) q31; ry(-pi/4) q32; ry(-pi/4) q33; ry(-pi/4) q34; ry(-pi/4) q35; ry(-pi/4) q36; ry(-pi/4) q37; ry(-pi/4) q38; ry(-pi/4) q39; ry(-pi/4) q40; ry(-pi/4) q41; ry(-pi/4) q42; ry(-pi/4) q43; ry(-pi/4) q44; ry(-pi/4) q45; ry(-pi/4) q46; ry(-pi/4) q47; ry(-pi/4) q48; ry(-pi/4) q49; ry(-pi/4) q50; ry(-pi/4) q51; ry(-pi/4) q52; ry(-pi/4) q53; ry(-pi/4) q54; ry(-pi/4) q55; ry(-pi/4) q56; ry(-pi/4) q57; ry(-pi/4) q58; ry(-pi/4) q59; ry(-pi/4) q60; ry(-pi/4) q61; ry(-pi/4) q62; ry(-pi/4) q63; }
gate circuit_171 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(pi/4) q0; ry(pi/4) q1; ry(pi/4) q2; ry(pi/4) q3; ry(pi/4) q4; ry(pi/4) q5; ry(pi/4) q6; ry(pi/4) q7; ry(pi/4) q8; ry(pi/4) q9; ry(pi/4) q10; ry(pi/4) q11; ry(pi/4) q12; ry(pi/4) q13; ry(pi/4) q14; ry(pi/4) q15; ry(pi/4) q16; ry(pi/4) q17; ry(pi/4) q18; ry(pi/4) q19; ry(pi/4) q20; ry(pi/4) q21; ry(pi/4) q22; ry(pi/4) q23; ry(pi/4) q24; ry(pi/4) q25; ry(pi/4) q26; ry(pi/4) q27; ry(pi/4) q28; ry(pi/4) q29; ry(pi/4) q30; ry(pi/4) q31; ry(pi/4) q32; ry(pi/4) q33; ry(pi/4) q34; ry(pi/4) q35; ry(pi/4) q36; ry(pi/4) q37; ry(pi/4) q38; ry(pi/4) q39; ry(pi/4) q40; ry(pi/4) q41; ry(pi/4) q42; ry(pi/4) q43; ry(pi/4) q44; ry(pi/4) q45; ry(pi/4) q46; ry(pi/4) q47; ry(pi/4) q48; ry(pi/4) q49; ry(pi/4) q50; ry(pi/4) q51; ry(pi/4) q52; ry(pi/4) q53; ry(pi/4) q54; ry(pi/4) q55; ry(pi/4) q56; ry(pi/4) q57; ry(pi/4) q58; ry(pi/4) q59; ry(pi/4) q60; ry(pi/4) q61; ry(pi/4) q62; ry(pi/4) q63; }
gate circuit_174 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(-pi/4) q0; ry(-pi/4) q1; ry(-pi/4) q2; ry(-pi/4) q3; ry(-pi/4) q4; ry(-pi/4) q5; ry(-pi/4) q6; ry(-pi/4) q7; ry(-pi/4) q8; ry(-pi/4) q9; ry(-pi/4) q10; ry(-pi/4) q11; ry(-pi/4) q12; ry(-pi/4) q13; ry(-pi/4) q14; ry(-pi/4) q15; ry(-pi/4) q16; ry(-pi/4) q17; ry(-pi/4) q18; ry(-pi/4) q19; ry(-pi/4) q20; ry(-pi/4) q21; ry(-pi/4) q22; ry(-pi/4) q23; ry(-pi/4) q24; ry(-pi/4) q25; ry(-pi/4) q26; ry(-pi/4) q27; ry(-pi/4) q28; ry(-pi/4) q29; ry(-pi/4) q30; ry(-pi/4) q31; ry(-pi/4) q32; ry(-pi/4) q33; ry(-pi/4) q34; ry(-pi/4) q35; ry(-pi/4) q36; ry(-pi/4) q37; ry(-pi/4) q38; ry(-pi/4) q39; ry(-pi/4) q40; ry(-pi/4) q41; ry(-pi/4) q42; ry(-pi/4) q43; ry(-pi/4) q44; ry(-pi/4) q45; ry(-pi/4) q46; ry(-pi/4) q47; ry(-pi/4) q48; ry(-pi/4) q49; ry(-pi/4) q50; ry(-pi/4) q51; ry(-pi/4) q52; ry(-pi/4) q53; ry(-pi/4) q54; ry(-pi/4) q55; ry(-pi/4) q56; ry(-pi/4) q57; ry(-pi/4) q58; ry(-pi/4) q59; ry(-pi/4) q60; ry(-pi/4) q61; ry(-pi/4) q62; ry(-pi/4) q63; }
gate circuit_177 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(pi/4) q0; ry(pi/4) q1; ry(pi/4) q2; ry(pi/4) q3; ry(pi/4) q4; ry(pi/4) q5; ry(pi/4) q6; ry(pi/4) q7; ry(pi/4) q8; ry(pi/4) q9; ry(pi/4) q10; ry(pi/4) q11; ry(pi/4) q12; ry(pi/4) q13; ry(pi/4) q14; ry(pi/4) q15; ry(pi/4) q16; ry(pi/4) q17; ry(pi/4) q18; ry(pi/4) q19; ry(pi/4) q20; ry(pi/4) q21; ry(pi/4) q22; ry(pi/4) q23; ry(pi/4) q24; ry(pi/4) q25; ry(pi/4) q26; ry(pi/4) q27; ry(pi/4) q28; ry(pi/4) q29; ry(pi/4) q30; ry(pi/4) q31; ry(pi/4) q32; ry(pi/4) q33; ry(pi/4) q34; ry(pi/4) q35; ry(pi/4) q36; ry(pi/4) q37; ry(pi/4) q38; ry(pi/4) q39; ry(pi/4) q40; ry(pi/4) q41; ry(pi/4) q42; ry(pi/4) q43; ry(pi/4) q44; ry(pi/4) q45; ry(pi/4) q46; ry(pi/4) q47; ry(pi/4) q48; ry(pi/4) q49; ry(pi/4) q50; ry(pi/4) q51; ry(pi/4) q52; ry(pi/4) q53; ry(pi/4) q54; ry(pi/4) q55; ry(pi/4) q56; ry(pi/4) q57; ry(pi/4) q58; ry(pi/4) q59; ry(pi/4) q60; ry(pi/4) q61; ry(pi/4) q62; ry(pi/4) q63; }
gate circuit_180 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(-pi/4) q0; ry(-pi/4) q1; ry(-pi/4) q2; ry(-pi/4) q3; ry(-pi/4) q4; ry(-pi/4) q5; ry(-pi/4) q6; ry(-pi/4) q7; ry(-pi/4) q8; ry(-pi/4) q9; ry(-pi/4) q10; ry(-pi/4) q11; ry(-pi/4) q12; ry(-pi/4) q13; ry(-pi/4) q14; ry(-pi/4) q15; ry(-pi/4) q16; ry(-pi/4) q17; ry(-pi/4) q18; ry(-pi/4) q19; ry(-pi/4) q20; ry(-pi/4) q21; ry(-pi/4) q22; ry(-pi/4) q23; ry(-pi/4) q24; ry(-pi/4) q25; ry(-pi/4) q26; ry(-pi/4) q27; ry(-pi/4) q28; ry(-pi/4) q29; ry(-pi/4) q30; ry(-pi/4) q31; ry(-pi/4) q32; ry(-pi/4) q33; ry(-pi/4) q34; ry(-pi/4) q35; ry(-pi/4) q36; ry(-pi/4) q37; ry(-pi/4) q38; ry(-pi/4) q39; ry(-pi/4) q40; ry(-pi/4) q41; ry(-pi/4) q42; ry(-pi/4) q43; ry(-pi/4) q44; ry(-pi/4) q45; ry(-pi/4) q46; ry(-pi/4) q47; ry(-pi/4) q48; ry(-pi/4) q49; ry(-pi/4) q50; ry(-pi/4) q51; ry(-pi/4) q52; ry(-pi/4) q53; ry(-pi/4) q54; ry(-pi/4) q55; ry(-pi/4) q56; ry(-pi/4) q57; ry(-pi/4) q58; ry(-pi/4) q59; ry(-pi/4) q60; ry(-pi/4) q61; ry(-pi/4) q62; ry(-pi/4) q63; }
gate circuit_183 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(pi/4) q0; ry(pi/4) q1; ry(pi/4) q2; ry(pi/4) q3; ry(pi/4) q4; ry(pi/4) q5; ry(pi/4) q6; ry(pi/4) q7; ry(pi/4) q8; ry(pi/4) q9; ry(pi/4) q10; ry(pi/4) q11; ry(pi/4) q12; ry(pi/4) q13; ry(pi/4) q14; ry(pi/4) q15; ry(pi/4) q16; ry(pi/4) q17; ry(pi/4) q18; ry(pi/4) q19; ry(pi/4) q20; ry(pi/4) q21; ry(pi/4) q22; ry(pi/4) q23; ry(pi/4) q24; ry(pi/4) q25; ry(pi/4) q26; ry(pi/4) q27; ry(pi/4) q28; ry(pi/4) q29; ry(pi/4) q30; ry(pi/4) q31; ry(pi/4) q32; ry(pi/4) q33; ry(pi/4) q34; ry(pi/4) q35; ry(pi/4) q36; ry(pi/4) q37; ry(pi/4) q38; ry(pi/4) q39; ry(pi/4) q40; ry(pi/4) q41; ry(pi/4) q42; ry(pi/4) q43; ry(pi/4) q44; ry(pi/4) q45; ry(pi/4) q46; ry(pi/4) q47; ry(pi/4) q48; ry(pi/4) q49; ry(pi/4) q50; ry(pi/4) q51; ry(pi/4) q52; ry(pi/4) q53; ry(pi/4) q54; ry(pi/4) q55; ry(pi/4) q56; ry(pi/4) q57; ry(pi/4) q58; ry(pi/4) q59; ry(pi/4) q60; ry(pi/4) q61; ry(pi/4) q62; ry(pi/4) q63; }
gate circuit_186 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(-pi/4) q0; ry(-pi/4) q1; ry(-pi/4) q2; ry(-pi/4) q3; ry(-pi/4) q4; ry(-pi/4) q5; ry(-pi/4) q6; ry(-pi/4) q7; ry(-pi/4) q8; ry(-pi/4) q9; ry(-pi/4) q10; ry(-pi/4) q11; ry(-pi/4) q12; ry(-pi/4) q13; ry(-pi/4) q14; ry(-pi/4) q15; ry(-pi/4) q16; ry(-pi/4) q17; ry(-pi/4) q18; ry(-pi/4) q19; ry(-pi/4) q20; ry(-pi/4) q21; ry(-pi/4) q22; ry(-pi/4) q23; ry(-pi/4) q24; ry(-pi/4) q25; ry(-pi/4) q26; ry(-pi/4) q27; ry(-pi/4) q28; ry(-pi/4) q29; ry(-pi/4) q30; ry(-pi/4) q31; ry(-pi/4) q32; ry(-pi/4) q33; ry(-pi/4) q34; ry(-pi/4) q35; ry(-pi/4) q36; ry(-pi/4) q37; ry(-pi/4) q38; ry(-pi/4) q39; ry(-pi/4) q40; ry(-pi/4) q41; ry(-pi/4) q42; ry(-pi/4) q43; ry(-pi/4) q44; ry(-pi/4) q45; ry(-pi/4) q46; ry(-pi/4) q47; ry(-pi/4) q48; ry(-pi/4) q49; ry(-pi/4) q50; ry(-pi/4) q51; ry(-pi/4) q52; ry(-pi/4) q53; ry(-pi/4) q54; ry(-pi/4) q55; ry(-pi/4) q56; ry(-pi/4) q57; ry(-pi/4) q58; ry(-pi/4) q59; ry(-pi/4) q60; ry(-pi/4) q61; ry(-pi/4) q62; ry(-pi/4) q63; }
gate circuit_189 q0,q1,q2,q3,q4,q5,q6,q7,q8,q9,q10,q11,q12,q13,q14,q15,q16,q17,q18,q19,q20,q21,q22,q23,q24,q25,q26,q27,q28,q29,q30,q31,q32,q33,q34,q35,q36,q37,q38,q39,q40,q41,q42,q43,q44,q45,q46,q47,q48,q49,q50,q51,q52,q53,q54,q55,q56,q57,q58,q59,q60,q61,q62,q63 { ry(pi/4) q0; ry(pi/4) q1; ry(pi/4) q2; ry(pi/4) q3; ry(pi/4) q4; ry(pi/4) q5; ry(pi/4) q6; ry(pi/4) q7; ry(pi/4) q8; ry(pi/4) q9; ry(pi/4) q10; ry(pi/4) q11; ry(pi/4) q12; ry(pi/4) q13; ry(pi/4) q14; ry(pi/4) q15; ry(pi/4) q16; ry(pi/4) q17; ry(pi/4) q18; ry(pi/4) q19; ry(pi/4) q20; ry(pi/4) q21; ry(pi/4) q22; ry(pi/4) q23; ry(pi/4) q24; ry(pi/4) q25; ry(pi/4) q26; ry(pi/4) q27; ry(pi/4) q28; ry(pi/4) q29; ry(pi/4) q30; ry(pi/4) q31; ry(pi/4) q32; ry(pi/4) q33; ry(pi/4) q34; ry(pi/4) q35; ry(pi/4) q36; ry(pi/4) q37; ry(pi/4) q38; ry(pi/4) q39; ry(pi/4) q40; ry(pi/4) q41; ry(pi/4) q42; ry(pi/4) q43; ry(pi/4) q44; ry(pi/4) q45; ry(pi/4) q46; ry(pi/4) q47; ry(pi/4) q48; ry(pi/4) q49; ry(pi/4) q50; ry(pi/4) q51; ry(pi/4) q52; ry(pi/4) q53; ry(pi/4) q54; ry(pi/4) q55; ry(pi/4) q56; ry(pi/4) q57; ry(pi/4) q58; ry(pi/4) q59; ry(pi/4) q60; ry(pi/4) q61; ry(pi/4) q62; ry(pi/4) q63; }
qreg q[64];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_168 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
z q[1];
z q[2];
z q[3];
z q[5];
z q[6];
z q[7];
z q[9];
z q[13];
z q[15];
z q[16];
z q[17];
z q[19];
z q[20];
z q[21];
z q[22];
z q[24];
z q[25];
z q[26];
z q[28];
z q[29];
z q[30];
z q[35];
z q[37];
z q[38];
z q[39];
z q[41];
z q[42];
z q[43];
z q[44];
z q[46];
z q[47];
z q[48];
z q[50];
z q[51];
z q[52];
z q[59];
z q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_171 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
cz q[2],q[3];
cz q[6],q[7];
cz q[13],q[14];
cz q[15],q[16];
cz q[17],q[18];
cz q[19],q[20];
cz q[22],q[23];
cz q[24],q[25];
cz q[26],q[27];
cz q[28],q[29];
cz q[30],q[31];
cz q[35],q[36];
cz q[37],q[38];
cz q[39],q[40];
cz q[41],q[42];
cz q[44],q[45];
cz q[46],q[47];
cz q[48],q[49];
cz q[50],q[51];
cz q[52],q[53];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_174 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
z q[3];
z q[7];
z q[14];
z q[16];
z q[18];
z q[20];
z q[23];
z q[25];
z q[27];
z q[29];
z q[31];
z q[36];
z q[38];
z q[40];
z q[42];
z q[45];
z q[47];
z q[49];
z q[51];
z q[53];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_177 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
cz q[1],q[2];
cz q[3],q[13];
cz q[5],q[6];
cz q[7],q[17];
cz q[12],q[22];
cz q[14],q[15];
cz q[16],q[26];
cz q[18],q[19];
cz q[20],q[30];
cz q[23],q[24];
cz q[25],q[35];
cz q[27],q[28];
cz q[29],q[39];
cz q[34],q[44];
cz q[36],q[37];
cz q[38],q[48];
cz q[40],q[41];
cz q[42],q[52];
cz q[45],q[46];
cz q[49],q[50];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
cz q[5],q[15];
cz q[9],q[19];
cz q[12],q[13];
cz q[14],q[24];
cz q[16],q[17];
cz q[18],q[28];
cz q[20],q[21];
cz q[25],q[26];
cz q[27],q[37];
cz q[29],q[30];
cz q[31],q[41];
cz q[34],q[35];
cz q[36],q[46];
cz q[38],q[39];
cz q[40],q[50];
cz q[42],q[43];
cz q[47],q[48];
cz q[49],q[59];
cz q[51],q[52];
cz q[53],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_180 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
z q[1];
z q[3];
z q[5];
z q[7];
z q[9];
z q[12];
z q[14];
z q[16];
z q[18];
z q[22];
z q[23];
z q[25];
z q[27];
z q[29];
z q[31];
z q[34];
z q[36];
z q[38];
z q[40];
z q[44];
z q[45];
z q[47];
z q[49];
z q[51];
z q[53];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_183 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
cz q[1],q[13];
cz q[3],q[15];
cz q[5],q[17];
cz q[7],q[19];
cz q[9],q[21];
cz q[12],q[24];
cz q[14],q[26];
cz q[16],q[28];
cz q[18],q[30];
cz q[23],q[35];
cz q[25],q[37];
cz q[27],q[39];
cz q[29],q[41];
cz q[31],q[43];
cz q[34],q[46];
cz q[36],q[48];
cz q[38],q[50];
cz q[40],q[52];
cz q[47],q[59];
cz q[51],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_186 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
z q[2];
z q[3];
z q[6];
z q[7];
z q[12];
z q[13];
z q[15];
z q[16];
z q[17];
z q[19];
z q[21];
z q[24];
z q[25];
z q[26];
z q[28];
z q[29];
z q[30];
z q[34];
z q[35];
z q[37];
z q[38];
z q[39];
z q[41];
z q[43];
z q[46];
z q[47];
z q[48];
z q[50];
z q[51];
z q[52];
z q[59];
z q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
circuit_189 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];

### Steps to Reproduce

detailed above

### PR DESCRIPTION
**Pull request by ystade**
## Description

Issue #792 reported a bug which happened due to an unhelpful error message. This PR adds the example from the issue to the tests and improves the error message reported in that issue.

Fixes #792

## Checklist:

- [x] The pull request only contains commits that are focused and relevant to this change.
- [x] I have added appropriate tests that cover the new/changed functionality.
- [x] I have updated the documentation to reflect these changes.
- [x] I have added entries to the changelog for any noteworthy additions, changes, fixes, or removals.
- [x] I have added migration instructions to the upgrade guide (if needed).
- [x] The changes follow the project's style guidelines and introduce no new warnings.
- [x] The changes are fully tested and pass the CI checks.
- [x] I have reviewed my own code changes.

## Summary by CodeRabbit

- Bug Fixes
  - Improved compiler error message when placement fails, now offering guidance on adjusting window size or compiler configuration.

- Tests
  - Added a regression test to ensure compilation succeeds for a routing-aware scenario tied to a prior issue.

- Documentation
  - Updated changelog with the new error message entry and PR reference.

### CODE REVIEW

File: src/na/zoned/layout_synthesizer/placer/AStarPlacer.cpp [hunk 1]
```diff
@@ -119,7 +119,10 @@ auto AStarPlacer::aStarTreeSearch(
         "deepening_value and deepening_factor to reduce the number of explored "
         "nodes.");
   }
-  throw std::runtime_error("No path from start to any goal found.");
+  throw std::runtime_error("No path from start to any goal found. This may be "
+                           "caused by a too small window size. Try increasing,"
+                           "e.g., window_share to a higher value, e.g., 1.0"
+                           "in the compiler configuration.");
```
Comment (burgholzer) [inline src/na/zoned/layout_synthesizer/placer/AStarPlacer.cpp]: The wording here seems a bit odd to me.
How about:

> No path from start to any goal found. This may be caused by a too narrow window size. Try adjusting the `window_share` compiler configuration option to a higher value, such as `1.0`.

File: test/na/zoned/test_compiler.cpp [hunk 2]
```diff
@@ -201,4 +201,284 @@ TEST(RoutingAwareCompilerTest, Issue727) {
...
+circuit_189 q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];
+barrier q[0],q[1],q[2],q[3],q[4],q[5],q[6],q[7],q[8],q[9],q[10],q[11],q[12],q[13],q[14],q[15],q[16],q[17],q[18],q[19],q[20],q[21],q[22],q[23],q[24],q[25],q[26],q[27],q[28],q[29],q[30],q[31],q[32],q[33],q[34],q[35],q[36],q[37],q[38],q[39],q[40],q[41],q[42],q[43],q[44],q[45],q[46],q[47],q[48],q[49],q[50],q[51],q[52],q[53],q[54],q[55],q[56],q[57],q[58],q[59],q[60],q[61],q[62],q[63];)";
+
+TEST(RoutingAwareCompielrTest, Issue792) {
```
Comment (burgholzer) [inline test/na/zoned/test_compiler.cpp]:
```suggestion
TEST(RoutingAwareCompilerTest, Issue792) {
```

File: CHANGELOG.md [hunk 3]
```diff
@@ -16,6 +16,7 @@ This project adheres to [Semantic Versioning], with the exception that minor rel
 ### Fixed
 
 - 🐛 Fix logging level parameter values and error/warning messages ([#793]) ([**@ystade**])
+- 📝 Improve Error Message in NA Compiler ([#804]) ([**@ystade**])
```
Comment (burgholzer) [inline CHANGELOG.md]: New entries go on top ;-)

File: CHANGELOG.md [hunk 4]
```diff
@@ -15,6 +15,7 @@ This project adheres to [Semantic Versioning], with the exception that minor rel
 
 ### Changed
 
+- 📝 Improve Error Message in NA Compiler ([#804]) ([**@ystade**])
```
[the remark this answers is not in the document]
Comment (ystade) [reply CHANGELOG.md]: Should be fixed by the latest commit.

File: src/na/zoned/layout_synthesizer/placer/AStarPlacer.cpp [hunk 5]
```diff
@@ -119,7 +119,10 @@ auto AStarPlacer::aStarTreeSearch(
         "deepening_value and deepening_factor to reduce the number of explored "
         "nodes.");
   }
-  throw std::runtime_error("No path from start to any goal found.");
+  throw std::runtime_error(
+      "No path from start to any goal found. This may be caused by a too "
+      "narrow window size. Try adjusting the window_share compiler "
+      "configuration option to a higher value, such as 1.0.");
```
[the remark this answers is not in the document]
Comment (ystade) [reply src/na/zoned/layout_synthesizer/placer/AStarPlacer.cpp:125]: Will not do this.

File: CHANGELOG.md (hunk 4 above)
Comment (burgholzer) [inline CHANGELOG.md]:
```suggestion
- 📝 Improve error message in the NA compiler ([#804]) ([**@ystade**])
```

File: test/na/zoned/test_compiler.cpp [hunk 6]
```diff
@@ -201,4 +201,100 @@ TEST(RoutingAwareCompilerTest, Issue727) {
...
+cz q[49],q[50];
+)";
+
+TEST(RoutingAwareCompilerTest, Issue792) {
+  const auto qc = qasm3::Importer::imports(circuit792.data());
+  const auto arch = Architecture::fromJSONString(architectureSpecification792);
+  const auto config = nlohmann::json::parse(routingAwareConfiguration792);
+  RoutingAwareCompiler compiler(arch, config);
+  EXPECT_NO_THROW(std::ignore = compiler.compile(qc));
+}
```
[the remark this answers is not in the document]
Comment (ystade) [reply test/na/zoned/test_compiler.cpp:299]: I will not add this test.
